# Generated by Django 5.2.6 on 2025-09-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='product'),
            preserve_default=False,
        ),
    ]
