name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/yourrepo
          git fetch origin main
          git reset --hard origin/main
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py migrate --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
